server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    name: kodynguyen
    password: nggvaii
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service
